export const COPY = {
  brand: {
    name:    'ODORIKO',
    tagline: '踊り子',
  },
  nav: {
    guestMenu: 'Menu メニュー',
    admin:     'Admin',
    cart:      'Cart',
    search:    'Search',
  },
  menu: {
    heroEyebrow:  'Japanese Dining · Delivered to your door',
    heroTitle:    'Crafted for your finest moments',
    heroSubtitle: 'Every dish prepared by our kitchen team, using seasonal produce and premium-provenance ingredients sourced each morning.',
    filterAll:    'All 全て',
    available:    'available',
    perHead:      'per person',
    unavailable:  'Unavailable Today',
    addToCart:    'Add',
  },
  /** Japanese subtitles for each category shown under the English name */
  categoryJa: {
    Starters:        '前菜',
    Salads:          'サラダ',
    'Soups & Ramen': 'スープ・ラーメン',
    'From the Wok':  '炒め物',
    'Dim Sum & Bao': '点心・包',
    Skewers:         '串焼き',
    Robatayaki:      '炉端焼き',
    Sushi:           '寿司',
    Sides:           'サイド',
    Breakfast:       '朝食',
    Desserts:        'デザート',
    Beverages:       'ドリンク',
  } as Record<string, string>,
  cart: {
    title:        'Your Order',
    titleJa:      'ご注文',
    emptyTitle:   'Nothing here yet',
    emptySub:     'Add dishes from the menu to begin crafting your dining experience.',
    items:        (n: number) => `${n} item${n !== 1 ? 's' : ''}` as const,
    subtotal:     'Subtotal',
    delivery:     'Delivery',
    serviceFee:   'Service fee',
    vat:          (pct: number) => `VAT (${pct}%)` as const,
    total:        'Total',
    complimentary:'Complimentary',
    addMore:      'Add Items',
    checkout:     'Proceed to Checkout',
    orderNotes:   'Order notes',
    orderNotesHint: 'Special requests, allergies, delivery instructions...',
    customize:    'Customize',
    itemNotesHint:'e.g. no wasabi, extra spicy...',
    freeProgress: (amount: string) => `Add ${amount} more for free delivery` as const,
    freeEarned:   'You qualify for complimentary delivery!',
  },
  checkout: {
    title:        'Complete Your Order',
    stepAddress:  'Address',
    stepDelivery: 'Delivery',
    stepPayment:  'Payment',
    sectionAddress:  'Delivery address',
    sectionDelivery: 'Delivery option',
    sectionPayment:  'Payment method',
    placeOrder:   (total: string) => `Place Order — ${total}` as const,
    standard:     '35–50 min · Tracked delivery',
    express:      '15–20 min · Priority dispatch',
  },
  confirmation: {
    title:        'Order Confirmed',
    subtitle:     'Our kitchen is preparing your meal with care. You will receive updates as your order progresses.',
    reference:    'Order reference',
    returnMenu:   'Return to Menu',
    track: {
      confirmed:  'Confirmed',
      preparing:  'Preparing',
      enRoute:    'On the Way',
      delivered:  'Delivered',
    },
  },
  login: {
    title:       'Admin Login',
    subtitle:    'Sign in to manage your restaurant',
    password:    'Password',
    signIn:      'Sign In',
    demoNote:    'Demo credentials pre-filled',
    invalidPass: 'Invalid password',
    atmosphere:  'Where tradition meets craft',
  },
  admin: {
    nav: {
      dashboard:  'Dashboard',
      orders:     'Orders',
      products:   'Products',
      categories: 'Categories',
      delivery:   'Delivery & Fees',
      vat:        'Tax & VAT',
    },
    groups: {
      overview: 'Overview',
      catalog:  'Catalog',
      config:   'Configuration',
    },
    stats: {
      revenue:  'Revenue this week',
      orders:   'Total orders',
      active:   'Active orders',
      menu:     'Live menu items',
    },
    products: {
      title:    'Products',
      add:      '+ Add product',
      hide:     'Hide',
      show:     'Show',
      delete:   'Delete',
      live:     'Live',
      hidden:   'Hidden',
    },
    orders: {
      title:  'Orders',
    },
    settings: {
      save:   'Save changes',
      deliveryRates:    'Delivery rates',
      deliveryRatesSub: 'Set the fee shown to guests at checkout for each option.',
      serviceFee:       'Service fee',
      serviceFeeSub:    'A fixed operational fee applied to every order.',
      vatConfig:        'VAT configuration',
      vatConfigSub:     'Set the tax rate applied to all items, delivery, and fees.',
      taxSnapshot:      'Tax snapshot',
      taxSnapshotSub:   'Live view of your current tax settings.',
    },
  },
  contact: {
    heroEyebrow: 'Get in touch',
    heroTitle1: "LET'S",
    heroTitle2: 'TALK',
    heroAccent: 'Together',
    heroJp: 'お問い合わせ',
    heroSub: 'Have a question about our menu, want to make a reservation, or simply want to say hello — reach us directly on WhatsApp or through any of the channels below.',
    hoursTitle: 'Opening Hours　営業時間',
    hours: ['Mon – Thu   12:00 – 23:00', 'Fri – Sat   12:00 – 00:00', 'Sunday      12:00 – 22:00'],
    channelsLabel: 'Reach us',
    channelsLabelJp: '連絡先',
    channelsTitle: 'HOW TO FIND US',
    channelsTitleJp: '連絡方法',
    channels: [
      { label: 'WhatsApp', jp: 'ワッツアップ', value: '+20 128 900 8736', note: 'Fastest way to reach us', href: 'https://wa.me/201289008736', icon: 'whatsapp' as const },
      { label: 'Instagram', jp: 'インスタ', value: '@odoriko.eg', note: 'Daily specials & kitchen moments', href: 'https://www.instagram.com/odoriko.eg', icon: 'instagram' as const },
      { label: 'Location', jp: '場所', value: 'Arkan Plaza, Sheikh Zayed City, Egypt', note: 'Tap to open in Google Maps', href: 'https://maps.app.goo.gl/aXyHvDKLS4P9JYQ3A', icon: 'pin' as const },
      { label: 'Reserve a table', jp: '予約', value: 'Book via Dyne', note: 'Instant online reservations', href: 'https://eg.dyneapp.io/reservations/3108c960-d64d-11ef-8c01-83ec207791e4', icon: 'calendar' as const },
    ],
    formLabel: 'Send a message',
    formLabelJp: 'メッセージ',
    formTitle: 'WRITE TO US',
    formTitleJp: 'お問い合わせフォーム',
    formReasonLabel: "What's this about?",
    formReasonLabelJp: 'お問い合わせ内容',
    formReasons: [
      { en: 'Menu question', jp: 'メニュー' },
      { en: 'Feedback', jp: 'フィードバック' },
      { en: 'Press', jp: 'プレス' },
      { en: 'Other', jp: 'その他' },
    ],
    formSubmitNote: 'We read everything. Expect a reply within 24 hours — usually sooner.',
    formSubmitBtn: 'SEND MESSAGE',
    locationLabel: 'Find us',
    locationLabelJp: '場所',
    locationTitleAr: 'الشيخ زايد · القاهرة',
    locationTitle: 'FIND',
    locationAccent: 'Odoriko',
    locationAddress: 'Arkan Plaza, Sheikh Zayed City, Egypt',
    locationAddressJp: 'アルカン・プラザ、シェイク・ザイード',
    locationDirections: 'Get directions',
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d215.91270841657487!2d31.00537722147725!3d30.01954424270293!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x14585b006162e039%3A0x71a53c91b2d27f6c!2sOdoriko!5e0!3m2!1sen!2seg!4v1775646877833!5m2!1sen!2seg',
    socialLabel: 'Follow us',
    socialLabelJp: 'フォロー',
    socialTitle: 'STAY CONNECTED',
    socialTitleJp: 'ソーシャルメディア',
    socialSub: 'Daily specials, kitchen moments, new menu items, and the occasional glimpse behind the pass. We show the work.',
    socials: [
      { name: 'INSTAGRAM', handle: '@odoriko.eg', href: 'https://www.instagram.com/odoriko.eg', icon: 'instagram' as const },
      { name: 'TIKTOK', handle: '@odoriko.eg', href: 'https://www.tiktok.com/@odoriko.eg', icon: 'tiktok' as const },
      { name: 'FACEBOOK', handle: 'Odoriko', href: 'https://www.facebook.com/people/Odoriko/61569708165306/', icon: 'facebook' as const },
      { name: 'WHATSAPP', handle: '+20 128 900 8736', href: 'https://wa.me/201289008736', icon: 'whatsapp' as const },
    ],
  },
  landing: {
    navLinks:     ['Menu メニュー', 'Our Story', 'Contact'],
    reserve:      'Reserve',
    orderNow:     'Order Now',
    heroEyebrow:  'Japanese Fine Dining · Cairo',
    heroTitle1:   'CRAFTED',
    heroTitle2:   'FOR YOUR',
    heroAccent:   'Finest',
    heroTitle3:   'MOMENTS',
    heroJp:       '最高のひとときのために',
    heroSub:      'Every dish prepared by our Michelin-trained kitchen team, using seasonal produce and premium-provenance ingredients sourced each morning.',
    heroExplore:  'Explore the Menu',
    heroStory:    'Our Story',
    statDishes:   'Dishes on menu',
    statYears:    'Years of craft',
    statRating:   'Average rating',
    openNow:      'Open now',
    openHours:    '12:00 — 23:00',
    openModes:    'Delivery · Dine-in · Takeaway',
    philLabel:    'Our Philosophy',
    philLabelJp:  '哲学',
    philTitle:    'WHERE',
    philAccent:   'Tradition',
    philTitle2:   'MEETS CRAFT',
    philBody:     'At Odoriko, every dish is a conversation between centuries of Japanese culinary tradition and the bold flavours of today. We source our fish directly, cut our own noodles, and brew our broths for 18 hours. Nothing is rushed. Nothing is compromised.',
    philQuoteJp:  '伝統と創造が交わる場所',
    philQuoteEn:  'Where tradition and creation meet',
    philLink:     'Read our full story',
    philCaption:  'Our kitchen · الطهي يبدأ هنا',
    featLabelJp:  '今週のおすすめ',
    featTitle:    "THIS WEEK'S FAVOURITES",
    featLink:     'View full menu',
    craftLabel:   'The Craft',
    craftLabelJp: '職人の技',
    craftTitle:   'BUILT ON',
    craftAccent:  'Ancient',
    craftTitle2:  'PRINCIPLES',
    craftBody:    'Japanese cuisine is one of the world\'s most disciplined culinary traditions. At Odoriko, we honour its three foundational principles in everything we serve.',
    pillars: [
      { num: '01', name: 'Shokunin Spirit', jp: '職人気質', desc: 'The craftsman\'s obsession with perfection — repeating the same technique ten thousand times until it becomes instinct.' },
      { num: '02', name: 'Shun — Seasonality', jp: '旬', desc: 'Ingredients at their precise peak. Our menu changes with the season, not our convenience.' },
      { num: '03', name: 'Ma — Negative Space', jp: '間', desc: 'The art of restraint. What is absent from the plate is as deliberate as what is present.' },
    ],
    catLabelJp:   'メニューカテゴリー',
    catTitle:     'EXPLORE THE MENU',
    catLink:      'All categories',
    bannerJp:     '今すぐご注文ください',
    bannerTitle:  'ORDER',
    bannerAccent: 'TONIGHT',
    bannerSub:    'Delivered to your door in under 45 minutes. Every dish made to order, never compromised for speed.',
    bannerOrder:  'Order Now',
    bannerReserve:'Reserve a Table',
    footerJp:     'Japanese Fine Dining · Cairo, Egypt',
    footerDesc:   'Crafted for your finest moments. Authentic Japanese cuisine, delivered with precision to your door.',
    footerMenu:   'The Menu',
    footerVisit:  'Visit Us',
    footerHours:  'Opening Hours',
    footerCopy:   '© 2026 Odoriko. All rights reserved.',
  },
  story: {
    heroEyebrow: 'The Story of Odoriko',
    heroTitle1: 'A STORY',
    heroTitle2: 'TOLD IN',
    heroAccent: 'Every Dish',
    heroJp: 'すべての料理が物語る',
    heroIntro: 'Odoriko was not built from a business plan. It was built from obsession — a decade of study in Japan, an unwavering belief that authentic Japanese cuisine belongs in Cairo, and the quiet conviction that craft is more powerful than trend.',
    heroScroll: 'Scroll to explore',
    heroYear: '2013',
    heroYearLabel: 'Founded',
    originLabel: 'The Beginning',
    originLabelJp: '始まり',
    originTitle: 'WHERE IT ALL',
    originAccent: 'Began',
    originJp: 'すべての始まり',
    originLede: 'It started with a meal in Kyoto that stopped time. A single piece of hirame, cut with a yanagiba, served on a cedar board worn smooth by thirty years of use. Nothing else. Nothing needed.',
    originBody: [
      'Our founder had been working in Cairo\'s restaurant industry for seven years when that meal happened. He had eaten well. He had eaten expensively. But he had never eaten like that — with full attention, surrounded by complete silence, tasting something that had been practised ten thousand times so it could be performed once, effortlessly.',
      'He stayed in Japan for three years. He trained under two chefs. He learned that Japanese cuisine is not a style — it is a discipline. A philosophy of restraint. A belief that the ingredient is the dish, and the chef\'s job is to stay out of the way.',
      'He returned to Cairo in 2013 with one goal: to build a place where that philosophy could take root. Not a Japanese-inspired restaurant. Not a fusion concept. A Japanese restaurant — honest, disciplined, and completely itself — in the middle of Cairo.',
    ],
    originQuote: '"The hardest thing I learned was not a technique. It was the courage to leave something off the plate."',
    originQuoteJp: '引き算の美学 — The aesthetic of subtraction',
    originQuoteAttr: '— Founder, Odoriko',
    bleedCaptionJp: 'مطبخنا · Our Kitchen',
    bleedCaptionTitle: 'WHERE THE WORK HAPPENS',
    bleedCaptionBody: 'Every service begins four hours before the first guest arrives. Broths are checked. Knife edges are tested against a sheet of paper. Rice is tasted. This is not preparation — this is the work.',
    timelineLabel: 'Our History',
    timelineLabelJp: '歴史',
    timelineTitleJp: '年表',
    timelineTitle: 'TEN YEARS OF CRAFT',
    timelineIntro: 'A decade is not built in dramatic moments. It is built in daily repetitions — in the 10,000 bowls of ramen that made the 10,001st perfect, and the quiet decision every year to hold the standard rather than compromise it.',
    timeline: [
      { year: '2013', jp: '開店', title: 'The doors open', body: 'Odoriko opens in Zamalek with 32 seats, a six-item menu, and a kitchen of four. The first week is fully booked within 48 hours. The second week, we run out of fish on Thursday.', image: '/brand/story/timeline-2013.webp', side: 'left' as const },
      { year: '2015', jp: 'ラーメン', title: 'The ramen counter launches', body: 'We add a dedicated ramen bar — eight seats, two broths, eighteen hours of cooking. It becomes the dish Odoriko is known for. The tonkotsu broth recipe has not changed since.', image: '/brand/story/timeline-2015.webp', side: 'right' as const },
      { year: '2017', jp: '拡張', title: 'The expansion', body: 'A second dining room is added — 60 new seats and a dedicated robatayaki grill station. We hire two new chefs trained in Osaka. The menu grows to 40 dishes. The standard does not move.', image: '/brand/story/timeline-2017.webp', side: 'left' as const },
      { year: '2020', jp: 'デリバリー', title: 'The hardest year — and a new beginning', body: 'The pandemic closes the dining room for six months. We launch delivery with the same kitchen, the same ingredients, and the same preparation. Over 14,000 orders in the first year.', image: '/brand/story/timeline-2020.webp', side: 'right' as const },
      { year: '2024', jp: '今日', title: 'Today — 84 dishes, one standard', body: 'Odoriko now serves 84 dishes across 10 categories. The kitchen employs 18 people. The tonkotsu broth is still 18 hours. The hirame is still cut with a yanagiba. Some things should not change.', image: '/brand/story/timeline-2024.webp', side: 'left' as const },
    ],
    galleryLabel: 'The Space',
    galleryLabelJp: '場所の記録',
    galleryTitle: 'THE',
    galleryAccent: 'Space',
    galleryIntro: 'The room was designed to disappear. Cedar, stone, and silence — a space where nothing competes with what is on the plate. These are the corners where meals become memories.',
    galleryImages: [
      { src: '/brand/story/gallery-dining.webp', name: 'Main Dining Room', jp: 'メインダイニング' },
      { src: '/brand/story/gallery-ramen.webp', name: 'Ramen Bar', jp: 'ラーメンカウンター' },
      { src: '/brand/story/gallery-kitchen.webp', name: 'Open Kitchen', jp: 'オープンキッチン' },
      { src: '/brand/story/gallery-private.webp', name: 'Private Dining', jp: '個室' },
      { src: '/brand/story/gallery-bar.webp', name: 'Sake & Whisky Bar', jp: '酒・ウイスキーバー' },
      { src: '/brand/story/gallery-counter.webp', name: 'Robatayaki Counter', jp: '炉端焼きカウンター' },
      { src: '/brand/story/gallery-entrance.webp', name: 'The Entrance', jp: '玄関' },
    ],
    numbers: [
      { val: '84', label: 'Dishes on menu', jp: 'メニュー数' },
      { val: '12', label: 'Years of craft', jp: '年の歴史' },
      { val: '18H', label: 'Our broth cooks', jp: 'スープの仕込み時間' },
      { val: '4.9', label: 'Average guest rating', jp: '平均評価' },
    ],
    valuesLabel: 'What We Believe',
    valuesLabelJp: '信念',
    valuesTitleJp: '三つの信念',
    valuesTitle: 'THREE BELIEFS',
    values: [
      { num: '01', name: 'SHOKUNIN', jp: '職人気質', desc: 'The craftsman\'s spirit. The belief that any single task — sharpening a knife, slicing a fish, folding a dumpling — deserves your full attention, every single time. Not because someone is watching. Because the task deserves it.' },
      { num: '02', name: 'SHUN', jp: '旬', desc: 'Seasonality as a discipline. We do not serve a dish because it is on the menu. We serve it because its ingredients are at their peak today — and only today. Convenience is never a reason. Season is the only reason.' },
      { num: '03', name: 'MA', jp: '間', desc: 'The art of negative space. What is absent from the plate is as considered as what is present. We resist addition. We resist garnish. We resist the temptation to show technique for its own sake. The ingredient must speak first.' },
    ],
    ctaJp: '今すぐご注文ください',
    ctaTitle: 'TASTE THE',
    ctaAccent: 'STORY',
  },
  marqueeItems: [
    { en: 'Robatayaki', jp: '炉端焼き' },
    { en: 'Omakase', jp: 'おまかせ' },
    { en: 'Wagyu', jp: '和牛' },
    { en: 'Sashimi', jp: '刺身' },
    { en: 'Ramen', jp: 'ラーメン' },
    { en: 'Yakitori', jp: '焼き鳥' },
    { en: 'Tempura', jp: '天ぷら' },
    { en: 'Dim Sum', jp: '点心' },
  ],
  errors: {
    network:      "Couldn't connect. Check your connection.",
    server:       'Something went wrong. Please try again.',
    notFound:     "We couldn't find what you were looking for.",
    unauthorized: 'Please sign in to continue.',
    forbidden:    "You don't have permission to do this.",
    conflict:     'This item is no longer available.',
    validation:   'Unexpected data format.',
    unknown:      'An unexpected error occurred.',
    tryAgain:     'Try again',
    goBack:       'Go back',
  },
  forms: {
    firstName:  'First name',
    lastName:   'Last name',
    street:     'Street address',
    city:       'City',
    postalCode: 'Postal code',
    phone:      'Phone',
    cardNumber: 'Card number',
    expiry:     'Expiry date',
    cvc:        'Security code',
    holder:     'Cardholder name',
    notes:      'Delivery notes (optional)',
  },
} as const;
