export const COPY = {
  brand: {
    name:    'ODORIKO',
    tagline: 'Fine Dining',
  },
  nav: {
    guestMenu: 'Guest Menu',
    admin:     'Admin',
    cart:      'Cart',
    search:    'Search',
  },
  menu: {
    heroEyebrow:  'Fine Dining · Delivered to your door',
    heroTitle:    'Crafted for your finest moments',
    heroSubtitle: 'Every dish prepared by our Michelin-trained kitchen team, using seasonal produce and premium-provenance ingredients sourced each morning.',
    filterAll:    'All',
    available:    'available',
    perHead:      'per head',
    unavailable:  'Unavailable Today',
    addToCart:    'Add',
  },
  cart: {
    title:        'Your Order',
    emptyTitle:   'Nothing here yet',
    emptySub:     'Add dishes from the menu to begin crafting your dining experience.',
    items:        (n: number) => `${n} item${n !== 1 ? 's' : ''}` as const,
    subtotal:     'Subtotal',
    delivery:     'Delivery',
    serviceFee:   'Service fee',
    vat:          (pct: number) => `VAT (${pct}%)` as const,
    total:        'Total',
    complimentary:'Complimentary',
    checkout:     'Proceed to Checkout',
    freeProgress: (amount: string) => `Add ${amount} more for free delivery` as const,
    freeEarned:   'You qualify for complimentary delivery!',
  },
  checkout: {
    title:        'Complete Your Order',
    stepAddress:  'Address',
    stepDelivery: 'Delivery',
    stepPayment:  'Payment',
    sectionAddress:  'Delivery address',
    sectionDelivery: 'Delivery option',
    sectionPayment:  'Payment method',
    placeOrder:   (total: string) => `Place Order — ${total}` as const,
    standard:     '35–50 min · Tracked delivery',
    express:      '15–20 min · Priority dispatch',
  },
  confirmation: {
    title:        'Order Confirmed',
    subtitle:     'Our kitchen is preparing your meal with care. You will receive updates as your order progresses.',
    reference:    'Order reference',
    returnMenu:   'Return to Menu',
    track: {
      confirmed:  'Confirmed',
      preparing:  'Preparing',
      enRoute:    'En Route',
      delivered:  'Delivered',
    },
  },
  admin: {
    nav: {
      dashboard:  'Dashboard',
      orders:     'Orders',
      products:   'Products',
      categories: 'Categories',
      delivery:   'Delivery & Fees',
      vat:        'Tax & VAT',
    },
    groups: {
      overview: 'Overview',
      catalog:  'Catalog',
      config:   'Configuration',
    },
    stats: {
      revenue:  'Revenue this week',
      orders:   'Total orders',
      active:   'Active orders',
      menu:     'Live menu items',
    },
    products: {
      title:    'Products',
      add:      '+ Add product',
      hide:     'Hide',
      show:     'Show',
      delete:   'Delete',
      live:     'Live',
      hidden:   'Hidden',
    },
    orders: {
      title:  'Orders',
    },
    settings: {
      save:   'Save changes',
      deliveryRates:    'Delivery rates',
      deliveryRatesSub: 'Set the fee shown to guests at checkout for each option.',
      serviceFee:       'Service fee',
      serviceFeeSub:    'A fixed operational fee applied to every order.',
      vatConfig:        'VAT configuration',
      vatConfigSub:     'Set the tax rate applied to all items, delivery, and fees.',
      taxSnapshot:      'Tax snapshot',
      taxSnapshotSub:   'Live view of your current tax settings.',
    },
  },
  errors: {
    network:      "Couldn't connect. Check your connection.",
    server:       'Something went wrong. Please try again.',
    notFound:     "We couldn't find what you were looking for.",
    unauthorized: 'Please sign in to continue.',
    forbidden:    "You don't have permission to do this.",
    conflict:     'This item is no longer available.',
    validation:   'Unexpected data format.',
    unknown:      'An unexpected error occurred.',
    tryAgain:     'Try again',
    goBack:       'Go back',
  },
  forms: {
    firstName:  'First name',
    lastName:   'Last name',
    street:     'Street address',
    city:       'City',
    postalCode: 'Postal code',
    phone:      'Phone',
    cardNumber: 'Card number',
    expiry:     'Expiry date',
    cvc:        'Security code',
    holder:     'Cardholder name',
    notes:      'Delivery notes (optional)',
  },
} as const;