export const COPY = {
  brand: {
    name:    'ODORIKO',
    tagline: '踊り子',
  },
  nav: {
    guestMenu: 'Menu メニュー',
    admin:     'Admin',
    cart:      'Cart',
    search:    'Search',
  },
  menu: {
    heroEyebrow:  'Japanese Dining · Delivered to your door',
    heroTitle:    'Crafted for your finest moments',
    heroSubtitle: 'Every dish prepared by our kitchen team, using seasonal produce and premium-provenance ingredients sourced each morning.',
    filterAll:    'All 全て',
    available:    'available',
    perHead:      'per person',
    unavailable:  'Unavailable Today',
    addToCart:    'Add',
  },
  /** Japanese subtitles for each category shown under the English name */
  categoryJa: {
    Starters:        '前菜',
    Salads:          'サラダ',
    'Soups & Ramen': 'スープ・ラーメン',
    'From the Wok':  '炒め物',
    'Dim Sum & Bao': '点心・包',
    Skewers:         '串焼き',
    Robatayaki:      '炉端焼き',
    Sushi:           '寿司',
    Sides:           'サイド',
    Breakfast:       '朝食',
    Desserts:        'デザート',
    Beverages:       'ドリンク',
  } as Record<string, string>,
  cart: {
    title:        'Your Order',
    titleJa:      'ご注文',
    emptyTitle:   'Nothing here yet',
    emptySub:     'Add dishes from the menu to begin crafting your dining experience.',
    items:        (n: number) => `${n} item${n !== 1 ? 's' : ''}` as const,
    subtotal:     'Subtotal',
    delivery:     'Delivery',
    serviceFee:   'Service fee',
    vat:          (pct: number) => `VAT (${pct}%)` as const,
    total:        'Total',
    complimentary:'Complimentary',
    checkout:     'Proceed to Checkout',
    freeProgress: (amount: string) => `Add ${amount} more for free delivery` as const,
    freeEarned:   'You qualify for complimentary delivery!',
  },
  checkout: {
    title:        'Complete Your Order',
    stepAddress:  'Address',
    stepDelivery: 'Delivery',
    stepPayment:  'Payment',
    sectionAddress:  'Delivery address',
    sectionDelivery: 'Delivery option',
    sectionPayment:  'Payment method',
    placeOrder:   (total: string) => `Place Order — ${total}` as const,
    standard:     '35–50 min · Tracked delivery',
    express:      '15–20 min · Priority dispatch',
  },
  confirmation: {
    title:        'Order Confirmed',
    subtitle:     'Our kitchen is preparing your meal with care. You will receive updates as your order progresses.',
    reference:    'Order reference',
    returnMenu:   'Return to Menu',
    track: {
      confirmed:  'Confirmed',
      preparing:  'Preparing',
      enRoute:    'En Route',
      delivered:  'Delivered',
    },
  },
  login: {
    title:       'Admin Login',
    subtitle:    'Sign in to manage your restaurant',
    password:    'Password',
    signIn:      'Sign In',
    demoNote:    'Demo credentials pre-filled',
    invalidPass: 'Invalid password',
    atmosphere:  'Where tradition meets craft',
  },
  admin: {
    nav: {
      dashboard:  'Dashboard',
      orders:     'Orders',
      products:   'Products',
      categories: 'Categories',
      delivery:   'Delivery & Fees',
      vat:        'Tax & VAT',
    },
    groups: {
      overview: 'Overview',
      catalog:  'Catalog',
      config:   'Configuration',
    },
    stats: {
      revenue:  'Revenue this week',
      orders:   'Total orders',
      active:   'Active orders',
      menu:     'Live menu items',
    },
    products: {
      title:    'Products',
      add:      '+ Add product',
      hide:     'Hide',
      show:     'Show',
      delete:   'Delete',
      live:     'Live',
      hidden:   'Hidden',
    },
    orders: {
      title:  'Orders',
    },
    settings: {
      save:   'Save changes',
      deliveryRates:    'Delivery rates',
      deliveryRatesSub: 'Set the fee shown to guests at checkout for each option.',
      serviceFee:       'Service fee',
      serviceFeeSub:    'A fixed operational fee applied to every order.',
      vatConfig:        'VAT configuration',
      vatConfigSub:     'Set the tax rate applied to all items, delivery, and fees.',
      taxSnapshot:      'Tax snapshot',
      taxSnapshotSub:   'Live view of your current tax settings.',
    },
  },
  landing: {
    navLinks:     ['Menu メニュー', 'Our Story', 'Gallery', 'Contact'],
    reserve:      'Reserve',
    orderNow:     'Order Now',
    heroEyebrow:  'Japanese Fine Dining · Cairo',
    heroTitle1:   'CRAFTED',
    heroTitle2:   'FOR YOUR',
    heroAccent:   'Finest',
    heroTitle3:   'MOMENTS',
    heroJp:       '最高のひとときのために',
    heroSub:      'Every dish prepared by our Michelin-trained kitchen team, using seasonal produce and premium-provenance ingredients sourced each morning.',
    heroExplore:  'Explore the Menu',
    heroStory:    'Our Story',
    statDishes:   'Dishes on menu',
    statYears:    'Years of craft',
    statRating:   'Average rating',
    openNow:      'Open now',
    openHours:    '12:00 — 23:00',
    openModes:    'Delivery · Dine-in · Takeaway',
    philLabel:    'Our Philosophy',
    philLabelJp:  '哲学',
    philTitle:    'WHERE',
    philAccent:   'Tradition',
    philTitle2:   'MEETS CRAFT',
    philBody:     'At Odoriko, every dish is a conversation between centuries of Japanese culinary tradition and the bold flavours of today. We source our fish directly, cut our own noodles, and brew our broths for 18 hours. Nothing is rushed. Nothing is compromised.',
    philQuoteJp:  '伝統と創造が交わる場所',
    philQuoteEn:  'Where tradition and creation meet',
    philLink:     'Read our full story',
    philCaption:  'Our kitchen · الطهي يبدأ هنا',
    featLabelJp:  '今週のおすすめ',
    featTitle:    "THIS WEEK'S FAVOURITES",
    featLink:     'View full menu',
    craftLabel:   'The Craft',
    craftLabelJp: '職人の技',
    craftTitle:   'BUILT ON',
    craftAccent:  'Ancient',
    craftTitle2:  'PRINCIPLES',
    craftBody:    'Japanese cuisine is one of the world\'s most disciplined culinary traditions. At Odoriko, we honour its three foundational principles in everything we serve.',
    pillars: [
      { num: '01', name: 'Shokunin Spirit', jp: '職人気質', desc: 'The craftsman\'s obsession with perfection — repeating the same technique ten thousand times until it becomes instinct.' },
      { num: '02', name: 'Shun — Seasonality', jp: '旬', desc: 'Ingredients at their precise peak. Our menu changes with the season, not our convenience.' },
      { num: '03', name: 'Ma — Negative Space', jp: '間', desc: 'The art of restraint. What is absent from the plate is as deliberate as what is present.' },
    ],
    catLabelJp:   'メニューカテゴリー',
    catTitle:     'EXPLORE THE MENU',
    catLink:      'All categories',
    bannerJp:     '今すぐご注文ください',
    bannerTitle:  'ORDER',
    bannerAccent: 'TONIGHT',
    bannerSub:    'Delivered to your door in under 45 minutes. Every dish made to order, never compromised for speed.',
    bannerOrder:  'Order Now',
    bannerReserve:'Reserve a Table',
    footerJp:     'Japanese Fine Dining · Cairo, Egypt',
    footerDesc:   'Crafted for your finest moments. Authentic Japanese cuisine, delivered with precision to your door.',
    footerMenu:   'The Menu',
    footerVisit:  'Visit Us',
    footerHours:  'Opening Hours',
    footerCopy:   '© 2025 Odoriko. All rights reserved.',
  },
  marqueeItems: [
    { en: 'Robatayaki', jp: '炉端焼き' },
    { en: 'Omakase', jp: 'おまかせ' },
    { en: 'Wagyu', jp: '和牛' },
    { en: 'Sashimi', jp: '刺身' },
    { en: 'Ramen', jp: 'ラーメン' },
    { en: 'Yakitori', jp: '焼き鳥' },
    { en: 'Tempura', jp: '天ぷら' },
    { en: 'Dim Sum', jp: '点心' },
  ],
  errors: {
    network:      "Couldn't connect. Check your connection.",
    server:       'Something went wrong. Please try again.',
    notFound:     "We couldn't find what you were looking for.",
    unauthorized: 'Please sign in to continue.',
    forbidden:    "You don't have permission to do this.",
    conflict:     'This item is no longer available.',
    validation:   'Unexpected data format.',
    unknown:      'An unexpected error occurred.',
    tryAgain:     'Try again',
    goBack:       'Go back',
  },
  forms: {
    firstName:  'First name',
    lastName:   'Last name',
    street:     'Street address',
    city:       'City',
    postalCode: 'Postal code',
    phone:      'Phone',
    cardNumber: 'Card number',
    expiry:     'Expiry date',
    cvc:        'Security code',
    holder:     'Cardholder name',
    notes:      'Delivery notes (optional)',
  },
} as const;
